apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      serviceAccount: thimo
      containers:
      - name: wordpress
        image: my_wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: wordpress
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_NAME
          value: thimo
        - name: DB_USER
          value: wordpress
        - name: DB_PASS
          value: harry
---
apiVersion: v1
kind: Service
metadata:
  annotations:
      metallb.universe.tf/allow-shared-ip: shared
  name: wordpress
  labels:
      app: wordpress
spec:
  selector:
    app: wordpress
  ports:
  - name: wordpress
    protocol: TCP
    port: 5050
  type: LoadBalancer
